INSERT INTO quotes (text, author) VALUES
  ('The secret of getting ahead is getting started.', 'Mark Twain'),
  ('It always seems impossible until it is done.', 'Nelson Mandela'),
  ('Do what you can, with what you have, where you are.', 'Theodore Roosevelt'),
  ('Action is the foundational key to all success.', 'Pablo Picasso'),
  ('Focus on being productive instead of busy.', 'Tim Ferriss'),
  ('Start where you are. Use what you have. Do what you can.', 'Arthur Ashe'),
  ('The only way to do great work is to love what you do.', 'Steve Jobs'),
  ('Believe you can and you are halfway there.', 'Theodore Roosevelt'),
  ('Success is not final, failure is not fatal: it is the courage to continue that counts.', 'Winston Churchill'),
  ('Don''t watch the clock; do what it does. Keep going.', 'Sam Levenson'),
  ('You don''t have to be great to start, but you have to start to be great.', 'Zig Ziglar'),
  ('The future depends on what you do today.', 'Mahatma Gandhi'),
  ('It''s not about being the best. It''s about being better than you were yesterday.', NULL),
  ('Small steps every day lead to big changes.', NULL),
  ('Done is better than perfect.', 'Sheryl Sandberg'),
  ('Work hard in silence, let your success be the noise.', 'Frank Ocean'),
  ('Productivity is never an accident. It is always the result of a commitment to excellence.', 'Paul J. Meyer'),
  ('The way to get started is to quit talking and begin doing.', 'Walt Disney'),
  ('Time you enjoy wasting is not wasted time.', 'Marthe Troly-Curtin'),
  ('If you spend too much time thinking about a thing, you''ll never get it done.', 'Bruce Lee'),
  ('You are never too old to set a new goal or dream a new dream.', 'C.S. Lewis'),
  ('Push yourself, because no one else is going to do it for you.', NULL),
  ('Great things never come from comfort zones.', NULL),
  ('Dream it. Wish it. Do it.', NULL),
  ('Success doesn''t just find you. You have to go out and get it.', NULL),
  ('The harder you work for something, the greater you''ll feel when you achieve it.', NULL),
  ('Don''t stop when you''re tired. Stop when you''re done.', NULL),
  ('Wake up with determination. Go to bed with satisfaction.', NULL),
  ('Do something today that your future self will thank you for.', NULL),
  ('Little things make big days.', NULL),
  ('It''s going to be hard, but hard does not mean impossible.', NULL),
  ('Don''t wait for opportunity. Create it.', NULL),
  ('Someday is not a day of the week.', 'Denise Brennan-Nelson'),
  ('You don''t need more time, you need to decide.', 'Seth Godin'),
  ('One task at a time, done well.', NULL);
